### ISSUE TITLE
发现一个 重大bug

### ISSUE THREAD

**Issue by luocaca** [llxdaxia/RestHttp#2]
api地址：http://www.luocaca.cn/hello-ssm/mountaineering/lately
get 请求 ：cn.lemon.resthttp.request.ConfigClient#configURLConnection 第一句   urlConnection.setDoOutput(true);  造成 get请求 变成post 请求。导致接口请求失败。
  需要楼主删掉那行代码。或者别的。

**Comment by zhazhaxin** [comment]
已更新到 1.0.8 版本
